# Generated by Django 5.2 on 2025-05-14 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numb_1', models.CharField(max_length=50, verbose_name='В сфере медицины')),
                ('numb_2', models.CharField(max_length=50, verbose_name='Специалистов в штабе')),
                ('numb_3', models.CharField(max_length=50, verbose_name='Довольных пациентов')),
                ('numb_4', models.CharField(max_length=50, verbose_name='Лицензированных аппаратов')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.CharField(max_length=150, verbose_name='Дата в виде текста')),
                ('main_desc', models.CharField(max_length=150, verbose_name='Главное описание')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='certificate', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone', models.CharField(max_length=50, verbose_name='Главный телефон')),
                ('phone', models.CharField(max_length=50, verbose_name='Второй телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
                ('schedule', models.CharField(max_length=150, verbose_name='График работы')),
                ('address', models.TextField(verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='DescSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('photo', models.ImageField(upload_to='licenses', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='ListProcedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.PositiveSmallIntegerField(verbose_name='Время прочтения')),
                ('photo', models.ImageField(upload_to='news', verbose_name='Фото')),
                ('main_desc', models.TextField(verbose_name='Вступительная часть новости')),
                ('desc', models.TextField(verbose_name='Текст новости')),
            ],
        ),
        migrations.CreateModel(
            name='RequirementsVacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('date', models.CharField(max_length=150, verbose_name='Дата в виде текста')),
                ('main_desc', models.CharField(max_length=150, verbose_name='Главное описание')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ManyToManyField(to='pages.listprocedures', verbose_name='Процедуры')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scope', verbose_name='Сфера деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.PositiveIntegerField(verbose_name='Стаж')),
                ('name', models.CharField(max_length=150, verbose_name='ФИ специалиста')),
                ('photo', models.ImageField(upload_to='specialist', verbose_name='Фото')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.scope', verbose_name='Сфера деятельности')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('main_desc', models.CharField(max_length=150, verbose_name='Главное описание')),
                ('photo', models.ImageField(upload_to='subscription', verbose_name='Фото')),
                ('old_price', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Старая цена')),
                ('new_price', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Новая цена')),
                ('desc', models.ManyToManyField(to='pages.descsubscription', verbose_name='Список содержимого абонемента')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.requirementsvacancies', verbose_name='Требование')),
            ],
        ),
    ]
