# Generated by Django 5.2 on 2025-05-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='requirement',
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirement',
            field=models.ManyToManyField(to='pages.requirementsvacancies', verbose_name='Требование'),
        ),
    ]
