# Generated by Django 5.2 on 2025-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='main_desc',
            field=models.TextField(verbose_name='Вступительная часть новости'),
        ),
    ]
